package model;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;

public class Game {

	
	private Player user;
	private ArrayList<Player> playersOnline;


	public Game() {

		
		user = new Player(null);
		playersOnline = new ArrayList<Player>();

		playersOnline.add(user);
		
		try {
			connectingPlayers();
		} catch (IOException e) {

			e.printStackTrace();
		}

	}

	public Player getUser() {
		
	return user;	
		
	}
	
	public void connectingPlayers() throws IOException {

		Random ran = new Random();

		FileReader fr = null;
		BufferedReader br = null;

		fr = new FileReader("./files/players.txt");
		br = new BufferedReader(fr);

		String nick = "";

		while ((nick = br.readLine()) != null) {

			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));
			playersOnline.add(new Player(nick));

		}

		if (br != null) {

			br.close();

		}

		if (fr != null) {

			fr.close();

		}

	}

	public ArrayList<Player> getPlayersOnline() {

		return playersOnline;

	}

}
